import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <div className="grid min-h-screen place-content-center p-4 sm:p-6 md:p-8 lg:12">
          <div className="w-full max-w-[min(100%,24rem)] space-y-4 sm:max-w-xl sm:space-y-5 md:max-w-2xl md:space-y-6 lg:max-w-3xl">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
