version: "3.9"
services:
  db:
    image: postgres:latest
    container_name: postgres_line_reserv
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Tokyo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/
    networks:
      - line_reserv_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # アプリケーションとDBとの接続周り設定
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api_line_reserv
    ports:
      - "8080:8080"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - line_reserv_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_line_reserv
    ports:
      - "3000:3000"
    environment:
      VITE_API_BASE_URL: /api/v1
    depends_on:
      - api
    networks:
      - line_reserv_network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  db_data:

# ipアドレス定義ではなくホスト名で指定することで利用をしやすくする
networks:
  line_reserv_network:
    driver: bridge
